In [54]:
import gym
import numpy as np
import pandas as pd
import random
from gym import envs
from IPython.display import display, clear_output
import warnings
warnings.filterwarnings('ignore')
from time import sleep

In [55]:
env = gym.make('Taxi-v3')

In [56]:
# Instantiate the scene states of the warehouse robot
state = env.reset()

print(f"Initial state: {state}")
# Checkout observable features of the warehouse robot interacting with its environment
#print("State space:", env.observation_space)
print("Time:", env.action_space)
print("Speed:", env.action_space)

# Exploring the state observation space

print("State Space {}".format(env.observation_space))

print("- DOWN:", env.observation_space)

print("- LEFT:", env.observation_space)

print("- RIGHT:", env.observation_space)

## Exploring action space

print("Action Space {}".format(env.action_space))


Initial state: 193
Time: Discrete(6)
Speed: Discrete(6)
State Space Discrete(500)
- DOWN: Discrete(500)
- LEFT: Discrete(500)
- RIGHT: Discrete(500)
Action Space Discrete(6)


In [59]:
## Reading from Dataset
iff = pd.read_csv('robot.csv', header=None)
view_matrix = iff.values

print(view_matrix)

[[ 0.00000000e+00  0.00000000e+00  1.00000000e+01  0.00000000e+00]
 [ 0.00000000e+00  3.00000000e+00  9.99314767e+00  2.61679781e-01]
 [ 0.00000000e+00  5.00000000e+00  9.98097349e+00  4.35778714e-01]
 ...
 [ 1.80000000e+02  1.75000000e+02 -1.90265095e-02 -4.35778714e-01]
 [ 1.80000000e+02  1.78000000e+02 -3.04586490e-03 -1.74497484e-01]
 [ 1.80000000e+02  1.80000000e+02  0.00000000e+00 -6.12323400e-16]]


In [60]:
env.render()

In [61]:
# Check out movements
maxrewards=0
obs= env.reset()
env.render()
for i in range(6):
    action = env.action_space.sample()
    obs, reward, done, info = env.step(action)
    maxrewards += reward
    env.render()
#List down rewards for every action
print("Tabulate-rewards: %r" % maxrewards)

Tabulate-rewards: -33


In [62]:
# Check out random space

env.P[126]

{0: [(1.0, 226, -1, False)],
 1: [(1.0, 26, -1, False)],
 2: [(1.0, 126, -1, False)],
 3: [(1.0, 106, -1, False)],
 4: [(1.0, 126, -10, False)],
 5: [(1.0, 126, -10, False)]}

In [38]:
# Qlearning

learn_rate = 0.2
qtable = np.zeros([env.observation_space.n, env.action_space.n])
discount = 0.4

for scene in range(1,2134):
    state = env.reset()
    done = False
    maxrewards = 0

    while done != True:
        action = np.argmax(qtable[state])
        state_new, reward, done, info = env.step(action)
        qtable[state,action] += learn_rate * (reward + discount * np.max(qtable[state_new,:]) - qtable[state,action])
        maxrewards = maxrewards + reward
        state = state_new
    if scene % 50 == 0:
        print('Scene {} Max Reward: {}'.format(scene,maxrewards))


Scene 50 Max Reward: -200
Scene 100 Max Reward: -200
Scene 150 Max Reward: -120
Scene 200 Max Reward: -200
Scene 250 Max Reward: -64
Scene 300 Max Reward: -81
Scene 350 Max Reward: -9
Scene 400 Max Reward: -37
Scene 450 Max Reward: -67
Scene 500 Max Reward: -18
Scene 550 Max Reward: -24
Scene 600 Max Reward: -29
Scene 650 Max Reward: -73
Scene 700 Max Reward: 13
Scene 750 Max Reward: -37
Scene 800 Max Reward: 11
Scene 850 Max Reward: -46
Scene 900 Max Reward: 4
Scene 950 Max Reward: -89
Scene 1000 Max Reward: 7
Scene 1050 Max Reward: 9
Scene 1100 Max Reward: 2
Scene 1150 Max Reward: 9
Scene 1200 Max Reward: -2
Scene 1250 Max Reward: 7
Scene 1300 Max Reward: 7
Scene 1350 Max Reward: 6
Scene 1400 Max Reward: 8
Scene 1450 Max Reward: -2
Scene 1500 Max Reward: -13
Scene 1550 Max Reward: 4
Scene 1600 Max Reward: -3
Scene 1650 Max Reward: -12
Scene 1700 Max Reward: 9
Scene 1750 Max Reward: 5
Scene 1800 Max Reward: 3
Scene 1850 Max Reward: -8
Scene 1900 Max Reward: 4
Scene 1950 Max Reward: 2


In [41]:

env.reset()

state = env.reset()
step = 0
done = False
print("****************************************************")
print("STARTING ")
env.render()
for step in range(maxrewards):

    # Take the action (index) that have the maximum expected future reward given that state
    action = np.argmax(qtable[state,:])

    new_state, reward, done, info = env.step(action)


    env.render()

    # We print the current step.
    print("Number of steps", step)
    if done:
      break
    state = new_state
env.close()

****************************************************
STARTING 
Number of steps 0
Number of steps 1
